---
# tasks file for ansible-smokeping

- name: install packages
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items:
  - nginx 
  - smokeping

#- name: create python symlinks
-  file:
    src:  /usr/local/bin/python2.7
    dest: /usr/local/bin/python
    state: link

-  file:
    src: /usr/local/bin/python2.7-config
    dest: /usr/local/bin/python-config
    state: link

-  file:
    src: /usr/local/bin/python2.7-2to3
    dest: /usr/local/bin/2to3
    state: link

-  file:
    src: /usr/local/bin/pydoc2.7
    dest: /usr/local/bin/pydoc
    state: link

- file:
    path: /var/db/smokeping/
    state: directory
    mode: 0755
    owner: _smokeping
    group: _smokeping

