---
- service:
    name: smokeping
    state: started
    enabled: yes

- service:
    name: smokeping_fcgi
    state: started
    enabled: yes

- service:
    name: nginx
    state: started
    enabled: yes

